# Generated by Django 2.2 on 2019-04-05 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilteredWord',
            fields=[
                ('word', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Word')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='User Name')),
                ('password', models.CharField(max_length=20, unique=True, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='Email')),
                ('coin', models.IntegerField(default=100, verbose_name='Coin')),
                ('brain_score', models.IntegerField(default=0, verbose_name='Brain')),
                ('validity', models.IntegerField(default=0, verbose_name='Validity')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_content', models.TextField(max_length=150, verbose_name='Text')),
                ('answer', models.CharField(max_length=25, verbose_name='Answer')),
                ('difficulty', models.FloatField(verbose_name='difficulty')),
                ('activity', models.BooleanField(verbose_name='Activity')),
                ('category', models.CharField(max_length=20, verbose_name='category')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('fk_maker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Player')),
            ],
        ),
        migrations.CreateModel(
            name='WordList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20, verbose_name='Word')),
                ('similarity_percent', models.FloatField(verbose_name='Similarity Percent')),
                ('fk_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Question')),
            ],
            options={
                'unique_together': {('word', 'fk_question')},
            },
        ),
        migrations.CreateModel(
            name='QuestionPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_status', models.BooleanField(verbose_name='Answer Status')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField()),
                ('is_playing', models.BooleanField(default=False, verbose_name='Is PLaying?')),
                ('fk_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Player')),
                ('fk_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Question')),
            ],
            options={
                'unique_together': {('fk_player', 'fk_question')},
            },
        ),
    ]
