# Generated by Django 2.2 on 2019-04-09 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='TowQuestionPlayer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_playing', models.BooleanField(default=True, verbose_name='is_playing')),
                ('fk_player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Player')),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.FloatField(default=0, verbose_name='difficulty'),
        ),
        migrations.AlterField(
            model_name='questionplayer',
            name='end_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.IntegerField(default=0, verbose_name='Winner')),
                ('score', models.FloatField(default=0, verbose_name='score')),
                ('fk_two_question_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TowQuestionPlayer')),
            ],
        ),
        migrations.AddField(
            model_name='towquestionplayer',
            name='fk_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Question'),
        ),
    ]
