# Generated by Django 2.2 on 2019-04-09 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190410_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='towquestionplayer',
            name='fk_player2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='main_towquestionplayers', to='main.Player'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='towquestionplayer',
            name='fk_player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_towquestionplayer_related', to='main.Player'),
        ),
    ]
